<a href="https://colab.research.google.com/github/roshanlaly364-dot/hackathone/blob/main/E-commerce_project/Data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv(r"C:\Users\ACER\OneDrive\Desktop\internal hack\archive\Kaggle_Ecommerce Data.csv")

In [ ]:
df.head()

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivered_date,region,returned,request_date,return_reason,total_amount,shipping_cost,profit_margin,customer_age,customer_gender
0,O100000,C17270,P234890,Home,164.08,0.15,1,Credit Card,23/12/2023,27/12/2023,West,No,NaN,NaN,139.47,7.88,31.17,60,Female
1,O100001,C17603,P228204,Grocery,24.73,0.00,1,Credit Card,3/4/2025,9/4/2025,South,No,NaN,NaN,24.73,4.60,-2.62,37,Male
2,O100002,C10860,P213892,Electronics,175.58,0.05,1,Credit Card,8/10/2024,12/10/2024,North,No,NaN,NaN,166.80,6.58,13.44,34,Male
3,O100003,C15390,P208689,Electronics,63.67,0.00,1,UPI,14/9/2024,20/9/2024,South,No,NaN,NaN,63.67,5.50,2.14,21,Female
4,O100004,C15226,P228063,Home,16.33,0.15,1,COD,21/12/2024,27/12/2024,East,No,NaN,NaN,13.88,2.74,1.15,39,Male

In [ ]:
df.shape

(34500, 19)

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 34500 entries, 0 to 34499
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         34500 non-null  str
 1   customer_id      34500 non-null  str
 2   product_id       34500 non-null  str
 3   category         34500 non-null  str
 4   price            34500 non-null  float64
 5   discount         34500 non-null  float64
 6   quantity         34500 non-null  int64
 7   payment_method   34500 non-null  str
 8   order_date       34500 non-null  str
 9   delivered_date   34500 non-null  str
 10  region           34500 non-null  str
 11  returned         34500 non-null  str
 12  request_date     1903 non-null   str
 13  return_reason    1903 non-null   str
 14  total_amount     34500 non-null  float64
 15  shipping_cost    34500 non-null  float64
 16  profit_margin    34500 non-null  float64
 17  customer_age     34500 non-null  int64
 18  customer_gender  34500 non-null  str
dtypes: float64(5), int64(2), str(12)
memory usage: 7.2 MB

In [ ]:
df.describe()

,price,discount,quantity,total_amount,shipping_cost,profit_margin,customer_age
count,34500.000000,34500.000000,34500.000000,34500.000000,34500.000000,34500.000000,34500.000000
mean,119.391632,0.049291,1.490725,170.008494,6.152120,28.116505,43.474377
std,195.620477,0.069894,0.932270,357.503014,2.389539,53.352947,14.980682
min,1.010000,0.000000,1.000000,0.820000,0.000000,-6.200000,18.000000
25%,16.690000,0.000000,1.000000,19.710000,4.420000,1.500000,31.000000
50%,45.660000,0.000000,1.000000,56.820000,6.090000,10.550000,43.000000
75%,130.950000,0.100000,2.000000,168.530000,7.830000,33.132500,56.000000
max,2930.470000,0.300000,5.000000,12931.800000,15.650000,1536.170000,69.000000

In [ ]:
df.columns

Index(['order_id', 'customer_id', 'product_id', 'category', 'price',
       'discount', 'quantity', 'payment_method', 'order_date',
       'delivered_date', 'region', 'returned', 'request_date', 'return_reason',
       'total_amount', 'shipping_cost', 'profit_margin', 'customer_age',
       'customer_gender'],
      dtype='str')

In [ ]:
df.isnull().sum()

order_id               0
customer_id            0
product_id             0
category               0
price                  0
discount               0
quantity               0
payment_method         0
order_date             0
delivered_date         0
region                 0
returned               0
request_date       32597
return_reason      32597
total_amount           0
shipping_cost          0
profit_margin          0
customer_age           0
customer_gender        0
dtype: int64

In [ ]:
df.tail()

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivered_date,region,returned,request_date,return_reason,total_amount,shipping_cost,profit_margin,customer_age,customer_gender
34495,O134495,C13553,P231412,Fashion,10.44,0.20,1,Debit Card,13/8/2025,16/8/2025,North,No,NaN,NaN,8.35,3.04,-0.12,23,Female
34496,O134496,C11349,P218266,Beauty,4.79,0.10,5,Debit Card,4/12/2023,10/12/2023,South,Yes,27/12/2023,No longer needed,21.56,3.37,6.33,61,Female
34497,O134497,C12986,P204345,Electronics,323.64,0.00,5,Credit Card,1/2/2025,7/2/2025,East,No,NaN,NaN,1618.20,12.18,182.00,41,Female
34498,O134498,C17196,P217644,Home,23.09,0.05,1,Credit Card,27/3/2024,2/4/2024,East,No,NaN,NaN,21.94,5.61,0.53,27,Female
34499,O134499,C13330,P207047,Home,76.84,0.00,1,Debit Card,11/9/2025,17/9/2025,East,No,NaN,NaN,76.84,7.57,13.95,19,Male

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df["order_id"].duplicated().sum()

np.int64(0)

In [ ]:
df["order_date"] = pd.to_datetime(df["order_date"], errors="coerce")
df["delivered_date"] = pd.to_datetime(df["delivered_date"], errors="coerce")
df["request_date"] = pd.to_datetime(df["request_date"], errors="coerce")

C:\Users\ACER\AppData\Local\Temp\ipykernel_31384\3339319408.py:1: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["order_date"] = pd.to_datetime(df["order_date"], errors="coerce")
C:\Users\ACER\AppData\Local\Temp\ipykernel_31384\3339319408.py:2: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["delivered_date"] = pd.to_datetime(df["delivered_date"], errors="coerce")
C:\Users\ACER\AppData\Local\Temp\ipykernel_31384\3339319408.py:3: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["request_date"] = pd.to_datetime(df["request_date"], errors="coerce")

In [ ]:
df.dtypes

order_id                      str
customer_id                   str
product_id                    str
category                      str
price                     float64
discount                  float64
quantity                    int64
payment_method                str
order_date         datetime64[us]
delivered_date     datetime64[us]
region                        str
returned                      str
request_date       datetime64[us]
return_reason                 str
total_amount              float64
shipping_cost             float64
profit_margin             float64
customer_age                int64
customer_gender               str
dtype: object

In [ ]:
(df["price"] <= 0).sum()

np.int64(0)

In [ ]:
(df["quantity"] <= 0).sum()

np.int64(0)

In [ ]:
df[df["request_date"] < df["order_date"]]

Empty DataFrame
Columns: [order_id, customer_id, product_id, category, price, discount, quantity, payment_method, order_date, delivered_date, region, returned, request_date, return_reason, total_amount, shipping_cost, profit_margin, customer_age, customer_gender]
Index: []

In [ ]:
df["delivery_days"] = (
    df["delivered_date"] - df["order_date"]
).dt.days

In [ ]:
df["delivery_days"].describe()

count    34500.000000
mean         4.814203
std          1.242141
min          3.000000
25%          4.000000
50%          5.000000
75%          6.000000
max         13.000000
Name: delivery_days, dtype: float64

In [ ]:
df["profit_margin"].describe()

count    34500.000000
mean        28.116505
std         53.352947
min         -6.200000
25%          1.500000
50%         10.550000
75%         33.132500
max       1536.170000
Name: profit_margin, dtype: float64

In [ ]:
df["customer_age"].describe()

count    34500.000000
mean        43.474377
std         14.980682
min         18.000000
25%         31.000000
50%         43.000000
75%         56.000000
max         69.000000
Name: customer_age, dtype: float64

In [ ]:
print("Orders:", df["order_id"].nunique())
print("Customers:", df["customer_id"].nunique())
print("Products:", df["product_id"].nunique())

Orders: 34500
Customers: 7903
Products: 24912

In [ ]:
pd.crosstab(df["returned"], df["request_date"].isna())

request_date  False  True
returned
No                0  32597
Yes            1903      0

In [ ]:
df["customer_gender"].value_counts(dropna=False)

customer_gender
Female    16818
Male      16310
Other      1372
Name: count, dtype: int64

In [ ]:
df["return_reason"] = df["return_reason"].fillna("Not Returned")

In [ ]:
df["request_date"]=df["request_date"].fillna("Not NEEDED")

In [ ]:
df.to_csv("cleaned_ecommerce_data.csv", index=False)

In [ ]:
cleaning_report = pd.DataFrame({
    "Column": df.columns,
    "Data_Type": df.dtypes.astype(str),
    "Missing_Count": df.isnull().sum().values,
    "Unique_Values": df.nunique().values
})

print(cleaning_report)

                          Column       Data_Type  Missing_Count  Unique_Values
order_id                order_id             str              0          34500
customer_id          customer_id             str              0           7903
product_id            product_id             str              0          24912
category                category             str              0              7
price                      price         float64              0          17274
discount                discount         float64              0              6
quantity                quantity           int64              0              5
payment_method    payment_method             str              0              6
order_date            order_date  datetime64[us]              0            731
delivered_date    delivered_date  datetime64[us]              0            737
region                    region             str              0              5
returned                returned             str              0              2
request_date        request_date          object              0            684
return_reason      return_reason             str              0              6
total_amount        total_amount         float64              0          18800
shipping_cost      shipping_cost         float64              0           1304
profit_margin      profit_margin         float64              0           9603
customer_age        customer_age           int64              0             52
customer_gender  customer_gender             str              0              3
delivery_days      delivery_days           int64              0             10